/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockPoolSol from "./MockPool.sol";
export type { mockPoolSol };
export type { MockIncentivesController } from "./MockIncentivesController";
export type { MockL2Pool } from "./MockL2Pool";
export type { MockReserveConfiguration } from "./MockReserveConfiguration";
